# 
# Vertx Configuration Options 
# to General Behaivour, Cluster, Metrics, DNS 
# http://vertx.io/docs/vertx-core/dataobjects.html
#
vertxOptions:
  # Number of event loop threads to be used  = 2 * number of cores on the machine
  eventLoopPoolSize: 8 
  # Number of threads in the worker pool
  workerPoolSize: 20
  # Number of threads in the internal blocking  pool (used by some internal operations)
  internalBlockingPoolSize: 20
  # Blocked thread check interval (millis)
  blockedThreadCheckInterval: 1000
  # Max event loop execute (nano seconds)
  maxEventLoopExecuteTime: 2000000000
  # Max worker execute time (nano seconds)
  maxWorkerExecuteTime:  60000000000
  # When a vert.x instance running a verticle dies abruptly, 
  # the verticle is migrated to another vertx instance. 
  # The vert.x instances must be in the same cluster
  # http://vertx.io/docs/vertx-core/java/#_high_availability_and_fail_over
  haEnabled: false
  # A quorum is the minimum number of votes that a distributed transaction 
  # has to obtain in order to be allowed to perform an operation in a distributed system.
  # http://vertx.io/docs/vertx-core/java/#_dealing_with_network_partitions_quora
  quorumSize: 1
  # HA group denotes a logical group of nodes in the cluster. 
  # Only nodes with the same HA group will failover onto one another. 
  haGroup: __DEFAULT__  
  # warning exception time (nanoseconds)
  # If a thread is blocked longer than this threshold, the warning log
  # contains a stack trace
  warningExceptionTime: 5000000000
  # File resolver caching enabled
  # wether the Vert.x file resolver uses caching for classpath resources
  fileResolverCachingEnabled: true
  # Vert.x metrics base configuration,
  metricsOptions:
    # whether metrics will be enabled on the Vert.x instance.
    enabled: false
  # the event bus configuration to configure the host, port, ssl...
  eventBusOptions:
    # Sets whether or not the event bus is clustered.
    clustered: false
    # the public facing hostname to be used for clustering
    clusterPublicHost: null
    # The public facing port to be used for clustering
    clusterPublicPort: 0
    # Set the value of cluster ping interval, in ms.
    clusterPingInterval: 20000
    # Set the value of cluster ping reply interval, in ms.
    clusterPingReplyInterval: 20000
    # The port
    port: 0
    # The host.
    host: localhost
    # Number of concurrent conections.
    acceptBacklog: -1
    # Whether client auth is required
    clientAuth: NONE
    # the value of reconnect attempts.
    reconnectAttempts: 0
    # The reconnect interval, in ms.
    reconnectInterval: 1000
    # The connect timeout, in ms.
    connectTimeout: 60000
    # Whether all server certificates should be trusted
    trustAll: true
  # Configuration options for Vert.x hostname resolver. 
  # The resolver uses the local hosts file and performs DNS A and AAAA queries
  addressResolverOptions:
    # the list of DNS server addresses, an address is the IP of the dns server, 
    # followed by an optional colon and a port, e.g 8.8.8.8 or {code 192.168.0.1:40000}. 
    # When the list is empty, the resolver will use the list of the system DNS server addresses from the environment, 
    # if that list cannot be retrieved it will use Google's public DNS servers "8.8.8.8" and "8.8.4.4".
    servers: null
    # True to enable the automatic inclusion in DNS queries of an optional record that hints the remote DNS server about how much data the resolver can read per response
    optResourceEnabled: true
    # the cache minimum TTL value in seconds. After resolution successful IP addresses are cached with their DNS response TTL, 
    # use this to set a minimum value to all responses TTL
    cacheMinTimeToLive: 0
    # the cache maximum TTL value in seconds. After successful resolution IP addresses are cached with their DNS response TTL, 
    # use this to set a maximum value to all responses TTL
    cacheMaxTimeToLive: 2147483647
    # the negative cache TTL value in seconds. After a failed hostname resolution, DNS queries won't be retried for a period of time equals to the negative TTL. 
    # This allows to reduce the response time of negative replies and reduce the amount of messages to DNS servers.
    cacheNegativeTimeToLive: 0
    # The query timeout in milliseconds
    queryTimeout: 5000
    # The maximum number of queries when an hostname is resolved
    maxQueries: 4
    # The DNS queries Recursion Desired flag value.
    rdFlag: true
    # The lists of DNS search domains
    searchDomains: null
    # The ndots value used when resolving using search domains, the default value is -1 which determines the value from the OS on Linux or uses the value 1
    ndots: -1
    # True to enable round-robin selection of the dns server to use
    rotateServers: false 
# The configuration options to Base Line Endpoint
baseLine:
  # The port to consumes the endpoint
  port: 8181
